"""empty message

Revision ID: 98b5f230502f
Revises: 61b0b1d2a3a4
Create Date: 2020-12-16 08:24:03.542513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b5f230502f'
down_revision = '61b0b1d2a3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'events', 'calendars', ['calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    # ### end Alembic commands ###
